-- Shared API throttling state. This table is intentionally not user-scoped:
-- public authentication routes need protection before a user is known, and
-- all API instances must see the same counter for a request key.
CREATE TABLE rate_limit_buckets (
  key_hash          text        NOT NULL,
  throttler_name    text        NOT NULL,
  total_hits        integer     NOT NULL DEFAULT 0,
  window_expires_at timestamptz NOT NULL,
  blocked_until     timestamptz,
  updated_at        timestamptz NOT NULL DEFAULT now(),

  PRIMARY KEY (key_hash, throttler_name),
  CONSTRAINT rate_limit_total_hits_nonnegative CHECK (total_hits >= 0)
);

CREATE INDEX rate_limit_expiry_idx
  ON rate_limit_buckets (window_expires_at);

COMMENT ON TABLE rate_limit_buckets IS
  'Shared fixed-window request counters; keys are SHA-256 hashes generated by Nest Throttler.';
